name: Deploy to ECR
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: ACCOUNT.dkr.ecr.REGION.amazonaws.com
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ACCOUNT.dkr.ecr.REGION.amazonaws.com
          ECR_REPOSITORY: my-sample-repo
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/my-image:$IMAGE_TAG .
          docker push $ECR_REGISTRY/my-image:$IMAGE_TAG
